/**
 * Offline support and "Add to Home Screen". The service worker itself is generated by
 * vite-plugin-pwa (see vite.config.ts); this module registers it, tells the visitor when the map
 * is saved for offline use or when a new version is ready, and drives the install button.
 */
import { registerSW } from 'virtual:pwa-register';
import { INSTALL_HINT_TEXT, installHint } from './installHint';

interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>;
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }>;
}

export function isStandalone(): boolean {
  return window.matchMedia?.('(display-mode: standalone)').matches || (navigator as Navigator & { standalone?: boolean }).standalone === true;
}

/** Manual install instructions for browsers without an install prompt (iPhone, in-app browsers). */
export function installHintText(): string | null {
  const hint = installHint({
    ua: navigator.userAgent,
    platform: navigator.platform,
    maxTouchPoints: navigator.maxTouchPoints || 0,
    standalone: isStandalone(),
  });
  return hint && INSTALL_HINT_TEXT[hint];
}

/** Holds Chrome/Edge/Samsung Internet's deferred install prompt so our own buttons can show it. */
class Installer {
  private deferred: BeforeInstallPromptEvent | null = null;
  private listeners = new Set<() => void>();

  /** Called once from setupPwa(), so importing this module stays side-effect free (unit tests). */
  listen() {
    window.addEventListener('beforeinstallprompt', (e) => {
      e.preventDefault();
      this.deferred = e as BeforeInstallPromptEvent;
      this.emit();
    });
    window.addEventListener('appinstalled', () => {
      this.deferred = null;
      this.emit();
      toast('Đã cài bản đồ vào màn hình chính.');
    });
  }

  get available() {
    return this.deferred !== null;
  }

  /** Calls `cb` now and on every change; returns an unsubscribe function. */
  onChange(cb: () => void) {
    this.listeners.add(cb);
    cb();
    return () => this.listeners.delete(cb);
  }

  async prompt() {
    const e = this.deferred;
    if (!e) return;
    // A prompt can only be shown once; the browser fires a new event if it may be offered again.
    this.deferred = null;
    this.emit();
    await e.prompt();
    await e.userChoice;
  }

  private emit() {
    for (const cb of this.listeners) cb();
  }
}

export const installer = new Installer();

let toastTimer = 0;
/** Small status message at the bottom of the screen, optionally with one action button. */
export function toast(message: string, action?: { label: string; run: () => void }, seconds = 6) {
  const box = document.getElementById('app-toast');
  if (!box) return;
  box.replaceChildren(document.createElement('span'));
  box.firstElementChild!.textContent = message;
  if (action) {
    const button = document.createElement('button');
    button.type = 'button';
    button.textContent = action.label;
    button.addEventListener('click', () => {
      box.hidden = true;
      action.run();
    });
    box.append(button);
  }
  box.hidden = false;
  clearTimeout(toastTimer);
  // An update prompt stays until it is used; plain notices fade out.
  if (!action) toastTimer = window.setTimeout(() => (box.hidden = true), seconds * 1000);
}

/** Install button and instructions on the start card. */
function bindStartCard() {
  const button = document.getElementById('install-btn');
  const hint = document.getElementById('install-hint');
  if (button) {
    button.addEventListener('click', () => void installer.prompt());
    installer.onChange(() => (button.hidden = !installer.available));
  }
  const text = installHintText();
  if (hint && text) {
    hint.textContent = text;
    hint.hidden = false;
  }
}

export function setupPwa() {
  installer.listen();
  bindStartCard();
  // Only production builds have a service worker; `pnpm dev` always serves fresh files.
  if (!import.meta.env.PROD || !('serviceWorker' in navigator)) return;
  const updateSW = registerSW({
    onOfflineReady: () => toast('Đã lưu bản đồ: lần sau mở được cả khi không có mạng.'),
    // Waits for the visitor instead of swapping files under a running tour.
    onNeedRefresh: () => toast('Đã có bản cập nhật của bản đồ.', { label: 'Cập nhật', run: () => void updateSW(true) }),
    onRegisteredSW: (_url, registration) => {
      // On event day the app may stay open for hours: look for a new version every hour.
      if (registration) {
        window.setInterval(() => {
          if (navigator.onLine) registration.update().catch(() => {});
        }, 60 * 60 * 1000);
      }
    },
    onRegisterError: (err) => console.warn('Offline mode is unavailable.', err),
  });
}
